include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: true
    cascade_invocations: false

analyzer:
  exclude:
    - lib/app/locator.config.dart
    - lib/generated/**
