name: elaichi
description: Campus guide of NIT Rourkela

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependency_overrides:
  # analyzer: "0.39.14"

dependencies:
  flutter:
    sdk: flutter

  # Logging
  logger: ^0.9.2

  # State management
  stacked: ^1.6.0

  # Navigation
  auto_route: ^0.6.6
  stacked_services: ^0.5.0

  # Inversion of control(dependency injection)
  get_it: ^5.0.3
  injectable: ^1.0.5
  dartz: ^0.9.1

  # Themes
  stacked_themes: ^0.2.2+2

  # Localisation
  easy_localization: ^2.3.3

  # Local database
  hive: ^1.4.3
  hive_flutter: ^0.3.1

  # GraphQL client library
  ferry: ^0.9.2
  gql_http_link: ^0.3.2
  ferry_hive_store: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.2.0
  mockito: ^4.1.1

  build_runner: ^1.10.0
  auto_route_generator: ^0.6.6
  injectable_generator: ^1.0.5

  # Local database
  hive_generator: ^0.7.1

  # GraphQL generators
  ferry_generator: ^0.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
